services:
  - type: web
    name: realtime-editor
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run prod
    envVars:
      - key: NODE_ENV
        value: production